### ISSUE TITLE
Issue on BuddyPress pages

### ISSUE THREAD

**Issue by madz00** [pojome/elementor#3710]
Navigating on BuddyPress pages after the update I get a blank page and error 500 from server and this error on php error log file:

PHP Fatal error: Uncaught Error: Call to a member function get_meta() on boolean in /wp-content/plugins/elementor/core/settings/page/manager.php:132

**Comment by pulla** [comment]
Hello, same as here ( Beta 2 )
We are using Elementor in BuddyPress themes.


`Fatal error: Uncaught Error: Call to a member function get_meta() on boolean in 
\htdocs\wp-content\plugins\elementor\core\settings\page\manager.php:132 Stack trace: #0 
\htdocs\wp-includes\class-wp-hook.php(286): 
Elementor\Core\Settings\Page\Manager->template_include('C:\\Bitnami\\wamp...') #1 \htdocs\wp-includes\plugin.php(203): 
WP_Hook->apply_filters('C:\\Bitnami\\wamp...', Array) #2 \htdocs\wp-includes\template-loader.php(73): apply_filters('template_includ...', 'C:\\Bitnami\\wamp...') #3 
\htdocs\wp-blog-header.php(19): require_once('C:\\Bitnami\\wamp...') #4 \htdocs\index.php(17): require('C:\\Bitnami\\wamp...') 
#5 {main} thrown in \htdocs\wp-content\plugins\elementor\core\settings\page\manager.php on line 132
`

Thank you for great plugin!

**Comment by mcpeanut** [comment]
Same here, I will be a little more descriptive on what is also happening on the front end of the website. When visiting any BuddyPress created pages with Elementor 2.0 or above The WordPress/Buddypress toolbar also disappears, this is the full error log below.

`[28-Mar-2018` 14:54:35 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_post() on boolean in /var/www/vhosts/mywebsite.com/httpdocs/wp-content/plugins/elementor/core/settings/page/manager.php:102
Stack trace:
#0 /var/www/vhosts/mywebsite.com/httpdocs/wp-content/plugins/elementor/core/settings/manager.php(159): Elementor\Core\Settings\Page\Manager->get_model_for_config()
#1 /var/www/vhosts/mywebsite.com/httpdocs/wp-content/plugins/elementor/includes/frontend.php(439): Elementor\Core\Settings\Manager::get_settings_frontend_config()
#2 /var/www/vhosts/mywebsite.com/httpdocs/wp-content/plugins/elementor/includes/frontend.php(541): Elementor\Frontend->enqueue_scripts()
#3 /var/www/vhosts/mywebsite.com/httpdocs/wp-includes/class-wp-hook.php(286): Elementor\Frontend->wp_footer('')
#4 /var/www/vhosts/mywebsite.com/httpdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/vhosts/mywebsite.com/httpdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /var/www/vhosts/ in /var/www/vhosts/mywebsite.com/httpdocs/wp-content/plugins/elementor/core/settings/page/manager.php on line 102`

**Comment by mcpeanut** [comment]
I forgot to add I have tested this on both OceanWP and Generate press themes with zero other plugins active, the issue happens when using a template created with Elementor for the header of the websites.

**Comment by pulla** [comment]
It has been solved after updating Beta 3( maybe ). and also not showing this error in V2
