### ISSUE TITLE
Fatal error by using Elementor-pro with PHP 5.5.15.

### ISSUE THREAD

**Issue by sushmak02** [pojome/elementor#3856]
## Description
As specified on your website Elementor also works with PHP 5.4+.
I am using PHP version 5.5.15. Also, Elementor v2.0 beta-3 is active on my site.
When Pro 2.0 Beta-1 is activated it gives a fatal error.
Refer - https://i.imgur.com/Bi2nlrF.png

## Steps to reproduce
PHP version - 5.5.15
Install and activate Elementor v2.0 beta-3.
Install and activate Pro 2.0 Beta-1.

## Environment

System Info -                     
== Server Environment ==
    Operating System: WINNT
    Software: Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.5.15
    MySQL version: 5.6.20
    PHP Version: 5.5.15
    PHP Max Input Vars: 1000
    PHP Max Post Size: 8M
    GD Installed: Yes
    Write Permissions: All right
    Elementor Library: Connected

== WordPress Environment ==
    Version: 4.9.4
    Site URL: http://192.168.1.137/wordpress
    Home URL: http://192.168.1.137/wordpress
    WP Multisite: No
    Max Upload Size: 2 MB
    Memory limit: 40M
    Permalink Structure: /%postname%/
    Language: en-US
    Timezone: 0
    Debug Mode: Inactive

== Theme ==
    Name: Astra
    Version: 1.2.5
    Author: Brainstorm Force
    Child Theme: No

== User ==
    Role: administrator
    WP Profile lang: en_US
    User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

== Active Plugins ==
    Elementor
        Version: 2.0.0-beta3
        Author: Elementor.com

    Ultimate Addons for Elementor
        Version: 1.0.0-beta.1
        Author: Brainstorm Force

== Debug ==
    Errors: There are no errors to display

**Comment by bainternet** [comment]
@sushmak02 

Not sure its related to the PHP version, what were you trying to do?
please provides steps to replicate.

**Comment by sushmak02** [comment]
I am certain it has to do with PHP version. I was trying to install elementor-pro beta version. But it gives fatal error when I activate this plugin. 
Now I have upgraded my PHP version to 7.2.3 and its working.

Steps - Try to use elementor-pro with PHP version 5.5.15

**Comment by epakrat** [comment]
@sushmak02  -

Even if it does have to do with PHP, I submit that's it's a non issue not worth the team's time especially having demonstrated that you can upgrade to a supported PHP version ( v7.2.x )and be fine. Let's not continue to support such outdated PHP versions is my vote (if I get one) and I'm not alone. Take a look at these...

https://wptavern.com/wordpress-to-bump-recommended-php-version-from-5-6-to-7-0-by-the-middle-of-2017

https://wptavern.com/a-plea-for-plugin-developers-to-stop-supporting-legacy-php-versions

Recommended PHP Version Increased to 7.2 in WordPress 4.9.5

Inside of the readme file in WordPress, the current recommended PHP version is 7.0. This version of PHP reached end of life last December. In 4.9.5, the recommend version is PHP 7.2. This is the same version that is recommended on WordPress.org. 

Bsides v5.5 is EOL and unsupported - https://secure.php.net/eol.php

The minimum version supported should be v5.6 IMO.

**Comment by sushmak02** [comment]
Hey @epakrat 

I do vote for not supporting outdated versions. I agree what your say. It is just I had to bring to notice when they say they support 5.4+ where as actually it doesn't.

Regards,
Sushma

**Comment by epakrat** [comment]
@sushmak02  - Ok. Understood. Let's hope they bump the minimum to for the v2 release to v5.6 then as that would be a requested feature in itself! :-)

**Comment by bainternet** [comment]
@sushmak02 

again, please provide actual steps to replicate. The error you have shown seems like you were trying to set a condition, On what? when? how? without that, there is not much we can do to help.

also make sure to update to Beta 4.

**Comment by bainternet** [comment]
Closing for lack of activity,

Feel free to reopen if the issue persists.

**Comment by leclerc-web** [comment]
Hi ,
I tried all PHP versions, I disabled all plugins and the site remains with a fatal error (error 500)

Do you have an idea ?



#0 /home/user/www/yann/wp-content/plugins/elementor-pro/base/module-base.php(60): ElementorPro\Modules\ThemeBuilder\Module->__construct()
#1 /home/leclercwtw/www/yann/wp-content/plugins/elementor-pro/includes/modules-manager.php(53): ElementorPro\Base\Module_Base::instance()
#2 /home/user/www/yann/wp-content/plugins/elementor-pro/plugin.php(252): ElementorPro\Manager->__construct()
#3 /home/user/www/yann/wp-includes/class-wp-hook.php(286): ElementorPro\Plugin->elementor_init('')
#4 /home/user/www/yann/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /home/user/www/yann/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /home/user/www/yann/wp-content/plugins/elementor/includes/plugin.php(469): do_action('elementor/init')
#7 /home/user/www in /home/leclercwtw/www/yann/wp-content/plugins/elementor-pro/modules/theme-builder/module.php on line 220

Thank you
