### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'Post ID #999 is not exist.

### ISSUE THREAD

**Issue by FragPeter** [pojome/elementor#3993]
Fatal error: Uncaught exception 'Exception' with message 'Post ID #999 is not exist.' in /is/htdocs/wp1047924_WDECA79I7J/www/wordpress/wp-content/plugins/elementor/core/base/document.php:632 Stack trace: #0 /is/htdocs/wp1047924_WDECA79I7J/www/wordpress/wp-content/plugins/elementor/core/document-types/post.php(158): Elementor\Core\Base\Document->__construct(Array) #1 /is/htdocs/wp1047924_WDECA79I7J/www/wordpress/wp-content/plugins/elementor/core/documents-manager.php(187): Elementor\Core\DocumentTypes\Post->__construct(Array) #2 /is/htdocs/wp1047924_WDECA79I7J/www/wordpress/wp-content/plugins/elementor/core/documents-manager.php(215): Elementor\Core\Documents_Manager->get(-999) #3 /is/htdocs/wp1047924_WDECA79I7J/www/wordpress/wp-content/plugins/elementor/modules/page-templates/module.php(55): Elementor\Core\Documents_Manager->get_doc_for_frontend(-999) #4 [internal function]: Elementor\Modules\PageTemplates\Module->template_include('/is/htdocs/wp10...') #5 /is/htdocs/wp1047924_WDECA79I7J/www/wordpress/wp-includes/class-wp- in /is/htdocs/wp1047924_WDECA79I7J/www/wordpress/wp-content/plugins/elementor/core/base/document.php on line 632

Server Environment |   
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | 5.6.37 |  
PHP Version: | 5.6.33-he.0 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 32M |  
GD Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

WordPress Environment |   |  
-- | -- | --
Version: | 4.9.4 |  
Site URL: | http://www.mydomain.de |  
Home URL: | http://www.mydomain.de
WP Multisite: | No |  
Max Upload Size: | 32 MB |  
Memory limit: | 40M | Wir empfehlen eine Einstellung von mindestens 64M. Für mehr Informationen, lese bitte wie erhöhe ich den Speicher für PHP.
Permalink Structure: | /%postname%/ |  
Language: | de-DE |  
Timezone: | Europe/Berlin |  
Admin Email: |   
Debug Mode: | Inactive

Theme
Name: | OceanWP |  
Version: | 1.5.10 |  
Author: | Nick

**Comment by bainternet** [comment]
@FragPeter 

please provide steps to replicate and try to:
please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).


And see if the issue still persists.

**Comment by bainternet** [comment]
Closing for lack of activity,

Feel free to reopen if the issue persists.
