### ISSUE TITLE
Shortcode bug

### ISSUE THREAD

**Issue by odedta** [pojome/elementor#4443]
I wrote a quick shortcode to add the Woocommerce cart to the header using the Shortcode widget
```
function add_cart_to_header() {
global $woocommerce;
$cart_html = '<a class="cart" href="' . $woocommerce->cart->get_cart_url() . '"><sub>' . $woocommerce->cart->cart_contents_count . '</sub><i class="fa fa-shopping-basket" aria-hidden="true"></i></a>';
echo $cart_html;
}
add_shortcode( 'add_cart_to_header', 'add_cart_to_header' );
```

When i'm trying to edit my template "Header" using Elementor I get a white screen with the following error:
`Fatal error: Uncaught Error: Call to a member function get_cart_url() on null in /home/yondrorc/public_html/leafoflife.life/wp-content/themes/oceanwp-child-theme/functions.php:97 Stack trace: #0 /home/yondrorc/public_html/leafoflife.life/wp-includes/shortcodes.php(319): add_cart_to_header('', '', 'add_cart_to_hea...') #1 [internal function]: do_shortcode_tag(Array) #2 /home/yondrorc/public_html/leafoflife.life/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(add_ca...', 'do_shortcode_ta...', '[add_cart_to_he...') #3 /home/yondrorc/public_html/leafoflife.life/wp-content/plugins/elementor/includes/widgets/shortcode.php(113): do_shortcode('[add_cart_to_he...') #4 /home/yondrorc/public_html/leafoflife.life/wp-content/plugins/elementor/includes/base/widget-base.php(499): Elementor\Widget_Shortcode->render() #5 /home/yondrorc/public_html/leafoflife.life/wp-content/plugins/elementor/includes/base/widget-base.php(605): Elementor\Widget_Base->render_content() #6 /home/yondrorc/public_html/leafoflife.life/wp-conte in /home/yondrorc/public_html/leafoflife.life/wp-content/themes/oceanwp-child-theme/functions.php on line 97`

Thanks

**Comment by odedta** [comment]
Prerequisites. - What do you mean by that?

Steps to replicate:
1. Copy & Paste that shortcode in your functions.php
2. Go to page edit and add a shortcode widget with the shortcode [add_cart_to_header]
3. Save the page
4. View the page - See the error

Isolating the problem. - ?

System info.
[system-info-leafoflife.life-15-05-2018.txt](https://github.com/pojome/elementor/files/2003740/system-info-leafoflife.life-15-05-2018.txt)

**Comment by odedta** [comment]
Well?
