### ISSUE TITLE
Woocommerce cart shortcode not working with Elementor

### ISSUE THREAD

**Issue by odedta** [pojome/elementor#5191]
Hello,

I placed this code in functions.php of OceanWP child theme.

```
global $woocommerce;
	
	$cart_count = $woocommerce->cart->cart_contents_count;
	$cart_total = $woocommerce->cart->get_cart_total();
	$cart_url   = wc_get_cart_url();
	
	if( !wp_is_mobile() ) {
		$html = '<i class="fa fa-shopping-cart" aria-hidden="true"></i> עגלה: <a class="cart-customlocation" href="' . $cart_url . '">' . sprintf ( _n( '%d פריט', '%d פריטים', $cart_count ), $cart_count ) . ' - ' . $cart_total . '</a>';
	}
	else {
		$html = '<a class="cart-customlocation" href="' . $cart_url . '"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a>';
	}
	return $html;
```

When I try to edit the header now I see the following error:
```
Notice: Trying to get property of non-object in /MY_PATH/public_html/wp-content/themes/oceanwp-child-theme/functions.php on line 113

Fatal error: Uncaught Error: Call to a member function get_cart_total() on null in /MY_PATH/public_html/wp-content/themes/oceanwp-child-theme/functions.php:114 Stack trace: 
#0 /MY_PATH/public_html/wp-includes/shortcodes.php(319): cart_in_header('', '', 'cart_in_header') 
#1 [internal function]: do_shortcode_tag(Array) 
#2 /MY_PATH/public_html/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(cart_i...', 'do_shortcode_ta...', '[cart_in_header...') 
#3 /MY_PATH/public_html/wp-content/plugins/elementor/includes/widgets/shortcode.php(130): do_shortcode('[cart_in_header...') 
#4 /MY_PATH/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(474): Elementor\Widget_Shortcode->render() 
#5 /MY_PATH/public_html/wp-content/plugins/elementor/includes/base/w in /MY_PATH/public_html/wp-content/themes/oceanwp-child-theme/functions.php on line 114
```

Which doesn't make sense because I called `global $woocommerce`, help!

Thanks

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
