### ISSUE TITLE
Incompatible with seo-optimized-images-business-woocommerce

### ISSUE THREAD

**Issue by kevin25** [pojome/elementor#5426]
Whenever I enable seo-optimized-images-business-woocommerce, the page built with Elementor is in mess.

Here is the log:

```
Stack trace:
#0 /home/domain/wp-includes/class-wp-hook.php(286): soi_load_custom_widget_output('<h3>Men's Shirt...', Array)
#1 /home/domain/wp-includes/plugin.php(203): WP_Hook->apply_filters('<h3>Men's Shirt...', Array)
#2 /home/domain/wp-content/plugins/elementor/includes/base/widget-base.php(388): apply_filters('widget_text', '<h3>Men's Shirt...', Array)
#3 /home/domain/wp-content/plugins/elementor/includes/widgets/text-editor.php(360): Elementor\Widget_Base->parse_text_editor('<h3>Men's Shirt...')
#4 /home/domain/wp-content/plugins/elementor/includes/base/widget-base.php(474): Elementor\Widget_Text_Editor->render()
#5 /home/domain/wp-content/plugins" while reading upstream, client: xxx.xxx.xxx.xxx, server: www.domain.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "www.domain.com"
2018/08/15 08:15:18 [error] 28644#0: *33558 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function soi_load_custom_widget_output(), 2 passed in /home/domain/wp-includes/class-wp-hook.php on line 286 and exactly 3 expected in /home/domain/wp-content/plugins/seo-optimized-images-business-woocommerce/seo-optimized-images.php:247
```

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.
